// <auto-generated />
namespace CafeArts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TestForCustom : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TestForCustom));
        
        string IMigrationMetadata.Id
        {
            get { return "202112161050426_TestForCustom"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
